### ISSUE TITLE
Unparseable date

### ISSUE THREAD

**Issue by gonjay** [gonjay/rubychina4android#15]
```
04-25 15:01:31.340    3638-3638/org.rubychina.app W/System.err﹕ java.text.ParseException: Unparseable date: "2014-04-25T14:58:17.406+08:00" (at offset 19)
04-25 15:01:31.340    3638-3638/org.rubychina.app W/System.err﹕ at java.text.DateFormat.parse(DateFormat.java:555)
04-25 15:01:31.340    3638-3638/org.rubychina.app W/System.err﹕ at org.rubychina.app.model.Topic.getShowTimeString(Topic.java:72)
04-25 15:01:31.340    3638-3638/org.rubychina.app W/System.err﹕ at org.rubychina.app.model.Topic.getLastReply(Topic.java:60)
04-25 15:01:31.340    3638-3638/org.rubychina.app W/System.err﹕ at org.rubychina.app.ui.adapter.TopicAdapter.getView(TopicAdapter.java:88)
04-25 15:01:31.340    3638-3638/org.rubychina.app W/System.err﹕ at com.haarman.listviewanimations.BaseAdapterDecorator.getView(BaseAdapterDecorator.java:83)
04-25 15:01:31.340    3638-3638/org.rubychina.app W/System.err﹕ at com.haarman.listviewanimations.swinginadapters.AnimationAdapter.getView(AnimationAdapter.java:129)
```

**Comment by gonjay** [comment]
Seems to fixed

Anyone can review it?
